coverage:
  precision: 2
  status:
    project:
      default:
        target: 100%
        threshold: 10%

ignore:
  - "**/benches/**"
  - "**/examples/**"
  - "**/fuzz/**"
  - "**/lib/e2e/**"
  - "**/lib/e2e-proc/**"
  - "**/templates/**"
