use proptest::prelude::*;

/// Creates a proptest strategy that generates non-empty vectors of random bytes.
///
/// This strategy ensures the generated vectors contain at least one element and
/// are suitable for testing cryptographic primitives that require non-empty inputs.
/// The maximum size of the generated vectors is determined by the proptest default
/// configuration.
///
/// # Returns
///
/// A proptest strategy that produces non-empty vectors of randomly generated bytes.
pub(crate) fn non_empty_u8_vec_strategy() -> impl Strategy<Value = Vec<u8>> {
    prop::collection::vec(
        any::<u8>(),
        1..ProptestConfig::default().max_default_size_range,
    )
}
