name: 🐞 Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["type: bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Briefly describe the issue you're experiencing. Tell us what you were trying to do and what happened instead. Remember, this is not a place to ask for help debugging code. For that, we welcome you in the OpenZeppelin Community Forum: https://forum.openzeppelin.com/.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: if you want, you can include screenshots as well :)
    validations:
      required: true
  - type: checkboxes
    id: platform
    attributes:
      label: platform
      description: On which operating system did this bug emerge?
      options:
        - label: linux
          required: false
        - label: windows
          required: false
        - label: macos
          required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
  - type: checkboxes
    id: terms
    attributes:
      label: Contribution Guidelines
      description: By submitting this issue, you agree to follow our [Contribution Guidelines](https://github.com/OpenZeppelin/rust-contracts-stylus/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Contribution Guidelines
          required: true
