= ERC-4262

https://eips.ethereum.org/EIPS/eip-4626[ERC-4626] is an extension of xref:erc20.adoc[ERC-20]  that proposes a standard interface for token vaults. This standard interface can be used by widely different contracts (including lending markets, aggregators, and intrinsically interest bearing tokens), which brings a number of subtleties. Navigating these potential issues is essential to implementing a compliant and composable token vault.

We provide a base implementation of ERC-4626 that includes a simple vault. This contract is designed in a way that allows developers to easily re-configure the vault’s behavior, with minimal overrides, while staying compliant. In this guide, we will discuss some security considerations that affect ERC-4626. We will also discuss common customizations of the vault

[[usage]]
== Usage

In order to make https://docs.rs/openzeppelin-stylus/0.1.1/openzeppelin_stylus/token/erc20/extensions/erc4262/index.html[`ERC-4262`] methods “external” so that other contracts can call them, you need to implement them by yourself for your final contract as follows:

[source,rust]
----
use alloy_primitives::{Address, U256};
use stylus_sdk::prelude::{entrypoint, public, storage};
use openzeppelin_stylus::{
    token::erc20::{
        extensions::{ Erc20Metadata, Erc4626, IErc20Metadata, IERC4626},
        Erc20, IErc20,
    },
    utils::{introspection::erc165::IErc165, Pausable},
};


#[entrypoint]
#[storage]
struct Erc4262xample {
    #[borrow]
    pub erc20: Erc20,
     #[borrow]
    pub metadata: Erc20Metadata,
    #[borrow]
    pub erc4626: Erc4626,
}


#[public]
#[inherit(Erc20, Erc20Metadata, Erc4626)]
impl Erc4262xample {
    fn max_deposit(&self, _receiver: Address) -> U256 {
        //self.metadata.decimals()
        U256::from(100)
    }
    // Add token minting feature.
}
----