= VestingWallet

A vesting wallet is an ownable contract that can receive native currency and
ERC-20 tokens, and release these assets to the wallet owner, also referred to as
"beneficiary", according to a vesting schedule.

Any assets transferred to this contract will follow the vesting schedule as if
they were locked from the beginning. Consequently, if the vesting has already
started, any amount of tokens sent to this contract will (at least partly) be
immediately releasable.

By setting the duration to 0, one can configure this contract to behave like
an asset timelock that hold tokens for a beneficiary until a specified time.

[NOTE]
====
Since the wallet is xref:ownable.adoc[Ownable], and ownership can be transferred,
it is possible to sell unvested tokens. Preventing this in a smart contract is
difficult, considering that: 1) a beneficiary address could be a counterfactually
deployed contract, 2) there is likely to be a migration path for EOAs to become
contracts in the near future.
====

[NOTE]
====
When using this contract with any token whose balance is adjusted automatically
(i.e. a rebase token), make sure to account the supply/balance adjustment in the
vesting schedule to ensure the vested amount is as intended.
====

[NOTE]
====
Chains with support for native ERC20s may allow the vesting wallet to withdraw
the underlying asset as both an ERC20 and as native currency. For example, if
chain C supports token A and the wallet gets deposited 100 A, then at 50% of
the vesting period, the beneficiary can withdraw 50 A as ERC20 and 25 A as
native currency (totaling 75 A). Consider disabling one of the withdrawal methods.
====



[[usage]]
== Usage

In order to make https://docs.rs/openzeppelin-stylus/0.2.0-alpha.4/openzeppelin_stylus/finance/vesting_wallet/index.html[`VestingWallet`] methods “external” so that other contracts can call them, you need to implement them by yourself for your final contract as follows:

[source,rust]
----
use openzeppelin_stylus::finance::vesting_wallet::VestingWallet;
use stylus_sdk::prelude::*;

#[entrypoint]
#[storage]
struct VestingWalletExample {
    #[borrow]
    vesting_wallet: VestingWallet,
}

#[public]
#[inherit(VestingWallet)]
impl VestingWalletExample {
    #[receive]
    fn receive(&mut self) -> Result<(), Vec<u8>> {
        Ok(())
    }
}
----

Additionally, you need to ensure proper initialization during xref:deploy.adoc[contract deployment]. Make sure to include the following code in your Solidity Constructor:

[source,solidity]
----
contract VestingWalletExample {
    address private _owner;

    uint256 private _released;
    mapping(address => uint256) private _erc20Released;
    uint64 private _start;
    uint64 private _duration;

    error OwnableInvalidOwner(address owner);

    constructor(
        address beneficiary,
        uint64 startTimestamp,
        uint64 durationSeconds
    ) payable {
        if (beneficiary == address(0)) {
            revert OwnableInvalidOwner(address(0));
        }
        _owner = beneficiary;

        _start = startTimestamp;
        _duration = durationSeconds;
    }
}
----
