[package]
name = "crypto-erc20"
description = "Template project for `openzeppelin-stylus` & `openzeppelin-crypto`"
version = "0.1.0"
publish = false
edition = "2021"
license = "MIT"

[dependencies]
openzeppelin-crypto = { path = "../../lib/crypto", features = ["ruint"] }
openzeppelin-stylus = { path = "../../contracts" }
# openzeppelin-stylus = { git = "https://github.com/OpenZeppelin/rust-contracts-stylus.git", rev = "ac58891bf6e90cccaf85282fe50838e891089a7d" }
# openzeppelin-crypto = { git = "https://github.com/OpenZeppelin/rust-contracts-stylus.git", rev = "ac58891bf6e90cccaf85282fe50838e891089a7d", features = [
#     "ruint",
# ] }

alloy-primitives = "=0.8.20"
stylus-sdk = "0.9.0"

[dev-dependencies]
# openzeppelin-stylus = { git = "https://github.com/OpenZeppelin/rust-contracts-stylus.git", rev = "ac58891bf6e90cccaf85282fe50838e891089a7d", features = [
#     "stylus-test",
# ] }

[features]
default = ["mini-alloc"]
# stylus-sdk/export-abi will be enabled automatically.
export-abi = ["openzeppelin-stylus/export-abi"]
debug = ["stylus-sdk/debug"]
mini-alloc = ["stylus-sdk/mini-alloc"]

[[bin]]
name = "crypto-erc20"
path = "src/main.rs"

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
codegen-units = 1
panic = "abort"
opt-level = "z"
strip = true
lto = true
debug = false
rpath = false
debug-assertions = false
incremental = false

[profile.dev]
panic = "abort"
