[package]
name = "crypto-erc20"
description = "Template project for `openzeppelin-stylus` & `openzeppelin-crypto`"
version = "0.1.0"
publish = false
edition = "2021"
license = "MIT"

[dependencies]
openzeppelin-crypto = { path = "../../lib/crypto", features = ["ruint"] }
openzeppelin-stylus = { path = "../../contracts" }

alloy-primitives = { version = "=0.8.20", default-features = false, features = [
    "tiny-keccak",
] }
stylus-sdk = "=0.9.0"

[dev-dependencies]
motsu = "=0.10.0"
arbitrary = { version = "1.4.1", features = ["derive"] }

[features]
default = ["mini-alloc"]
# stylus-sdk/export-abi will be enabled automatically.
export-abi = ["openzeppelin-stylus/export-abi"]
debug = ["stylus-sdk/debug"]
mini-alloc = ["stylus-sdk/mini-alloc"]

[[bin]]
name = "crypto-erc20"
path = "src/main.rs"

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
codegen-units = 1
panic = "abort"
opt-level = "z"
strip = true
lto = true
debug = false
rpath = false
debug-assertions = false
incremental = false

[profile.dev]
panic = "abort"
