name: Check Links
# This workflow checks that all links in the documentation are valid.
# It does this for antora docs(adoc) and markdown files.
# We prefer lycheeverse because it is faster, but doesn't support adoc files yet(https://github.com/lycheeverse/lychee/issues/291)
# Because of that, we use linkspector for adoc files and lychee for md files.
on:
  push:
    branches: [ main, v* ]
  pull_request:
    branches: [ main, v* ]

jobs:
  check-links:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress './**/*.md'
          fail: true

      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          fail_on_error: true
