name: publish motsu-proc
# This workflow publishes motsu-proc on crates.io.
permissions:
  contents: read
on:
  workflow_dispatch
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  check-publish:
    name: Publish motsu-proc on crates.io
    env:
      MOTSU_PROC_TOKEN: ${{ secrets.MOTSU_PROC_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Check motsu-proc
        run: cargo publish -p motsu-proc --dry-run

      - name: Publish motsu-proc
        run: cargo publish -p motsu-proc --token $MOTSU_PROC_TOKEN
